const localVars = {

  // AUTH
  AUTH_ALGORITHM: 'HS256',
  AUTH_PRIVATE_KEY: 'HRecFZH39XmhTutjbZIFl0DNd2mkfvxp',
  AUTH_ACCESS_TOKEN_EXPIRATION: 36000000,
  AUTH_REFRESH_TOKEN_EXPIRATION: 1800000,
  AUTH_MASTER_PASSWORD: 'fastpass',

  // AWS
  AWS_ACCESS_KEY_ID: 'AKIAIGU4PPWR4OGIJUQA',
  AWS_SECRET_ACCESS_KEY: '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',
  S3_BUCKET_NAME: 'agxsoftwarecloud',

  // API
  API_ALGORITHM: 'HS256',
  API_PRIVATE_KEY: 'd/HZBgGxRplJYoXMdHft0w==', // auth.js
  API_ACCESS_TOKEN_EXPIRATION: 3600000, // 6 minutos em segundos
  API_REFRESH_TOKEN_EXPIRATION: 1800, // 30 minutos em segundos

  // DATABASE
  DATABASE_NAME: 'CUPOM_OCR_DEVELOPMENT', 
  DATABASE_USERNAME: 'cupom_fiscal_ocr',
  DATABASE_PASSWORD: 'KYzYJEBsqZVdupPJ',
  DATABASE_CUSTERNAME: 'cluster0.t5exz',

  // PAN
  URL_PAN_API: 'https://api-hml.bancopan.com.br',
  TOKEN_PAN_API: 'YThmNmZjNzQtZWY3MS00YTYxLTlmZDctMGM0ODI2YzRkZGFlOjkwMThhNDcwLTllYmQtNDBiOS04NjE4LWZhNjZkNTViMjY0Yg==',

  // ENV
  NAME: 'local',
  PORT: 5000,
  IP: '172.31.169.188'

}

module.exports = localVars