const { 
  AUTH_ALGORITHM, 
  AUTH_PRIVATE_KEY,
  NAME,
  PORT,
  IP,
  AUTH_MASTER_PASSWORD,
  AUTH_ACCESS_TOKEN_EXPIRATION,
  AUTH_REFRESH_TOKEN_EXPIRATION 
} = require('./_variables')

const globals = {
  AUTH_REFRESH_TOKEN_EXPIRATION,
  AUTH_ACCESS_TOKEN_EXPIRATION,
  AUTH_MASTER_PASSWORD,
  AUTH_ALGORITHM, 
  AUTH_PRIVATE_KEY,
  NAME,
  PORT,
  IP,
   _genders: ['female', 'male', 'other']
}

export default globals 